spring.application.name=gestionEmploi
spring.datasource.url=http://localhost/phpmyadmin/index.php?route=/database/structure&db=gestiendesemplois
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



jwt.secret=
jwt.expiration=86400000

